
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 46;
  public static final int PLUSPLUS = 40;
  public static final int CBRACE = 30;
  public static final int Begin = 55;
  public static final int GTEQ = 53;
  public static final int MULT = 44;
  public static final int POWER = 35;
  public static final int OPAR = 24;
  public static final int LTEQ = 52;
  public static final int OBLOCK = 26;
  public static final int ELSIF = 9;
  public static final int CASE = 14;
  public static final int CPAR = 25;
  public static final int Var = 60;
  public static final int CONTINUE = 16;
  public static final int NumValue = 62;
  public static final int COMPARATOR = 37;
  public static final int PRINTLN = 21;
  public static final int MINUS = 42;
  public static final int FOR = 4;
  public static final int OBRACE = 28;
  public static final int ASIGNN = 54;
  public static final int OBRACKET = 31;
  public static final int AND = 49;
  public static final int NOT = 47;
  public static final int SEMICOLON = 23;
  public static final int StringConst = 59;
  public static final int LT = 57;
  public static final int NNOT = 48;
  public static final int CBRACKET = 29;
  public static final int OR = 45;
  public static final int IN = 5;
  public static final int COMMA = 33;
  public static final int EntryPoint = 12;
  public static final int PLUS = 41;
  public static final int ASSIGN = 36;
  public static final int IF = 7;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 43;
  public static final int RETURN = 6;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int MODULO = 50;
  public static final int TypeDef = 2;
  public static final int NEQ = 38;
  public static final int BRAK = 17;
  public static final int ANGBR = 51;
  public static final int BREAK = 22;
  public static final int EQ = 39;
  public static final int Identifier = 58;
  public static final int SWITCH = 13;
  public static final int Time = 63;
  public static final int COLON = 32;
  public static final int ELSE = 8;
  public static final int WHILE = 15;
  public static final int CLEAR = 20;
  public static final int END = 56;
  public static final int Type = 61;
  public static final int CBLOCK = 27;
  public static final int DEC = 34;
  public static final int FALSE = 11;
  public static final int MemDef = 3;
  public static final int DO = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TypeDef",
  "MemDef",
  "FOR",
  "IN",
  "RETURN",
  "IF",
  "ELSE",
  "ELSIF",
  "TRUE",
  "FALSE",
  "EntryPoint",
  "SWITCH",
  "CASE",
  "WHILE",
  "CONTINUE",
  "BRAK",
  "DOT",
  "DO",
  "CLEAR",
  "PRINTLN",
  "BREAK",
  "SEMICOLON",
  "OPAR",
  "CPAR",
  "OBLOCK",
  "CBLOCK",
  "OBRACE",
  "CBRACKET",
  "CBRACE",
  "OBRACKET",
  "COLON",
  "COMMA",
  "DEC",
  "POWER",
  "ASSIGN",
  "COMPARATOR",
  "NEQ",
  "EQ",
  "PLUSPLUS",
  "PLUS",
  "MINUS",
  "MINUSMINUS",
  "MULT",
  "OR",
  "DIVIDE",
  "NOT",
  "NNOT",
  "AND",
  "MODULO",
  "ANGBR",
  "LTEQ",
  "GTEQ",
  "ASIGNN",
  "Begin",
  "END",
  "LT",
  "Identifier",
  "StringConst",
  "Var",
  "Type",
  "NumValue",
  "Time"
  };
}

